[package]
name = "exs-playground"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
birei = { git = "https://github.com/Exolynk/birei", branch = "main", features = ["embedded"] }
exs-compiler = { path = "../../crates/exs-compiler" }
exs-runner = { path = "../../crates/exs-runner", default-features = false, features = ["browser"] }
leptos = { version = "0.7", features = ["csr"] }
pulldown-cmark = "0.13"
wasm-bindgen = "0.2.106"
web-sys = { version = "0.3.103", features = ["Element", "MouseEvent"] }
